apiVersion: v1
kind: Service
metadata:
  name: hotel-svc-stable
  namespace: hotel
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: hotel
    version: blue
  type: LoadBalancer